export const googleFontsList = [
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Nunito",
  "Poppins",
  "Ubuntu",
  "PT Sans",
  "Merriweather Sans",
  "Lobster",
  "Amatic SC",
  "Pacifico",
  "Raleway",
  "Cinzel",
  "Quicksand",
  "Zilla Slab",
  "Caveat",
  "Crimson Pro",
  "Bebas Neue",
  "Comfortaa",
  "Satisfy",
  "Permanent Marker",
  "Oswald",
  "Onset",
  "Bangers",
  "Kanit",
  "Work Sans",
  "Fira Sans",
  "Anton",
  "Playfair Display",
  "Rubik",
  "Alumni Sans",
  "Righteous",
  "Comico",
  "Excon",
  "Kalam",
  "Tanker",
  "Arsenal",
  "Balsamiq Sans",
  "Bona Nova SC",
] as const;
